version: '3'
services:
  app:
    build: .
    container_name: xsolla-example-client-side
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./target/:/usr/local/tomcat/webapps/
    command: [ "catalina.sh", "run" ]
    networks:
      - app-network

  ngrok:
    image: wernight/ngrok
    container_name: ngrok-xsolla-example-client-side
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
      - NGROK_PORT=app:8080
    ports:
      - "${NGROK_PORT}:4040"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
